### PR TITLE
Add support for variadic parameters and functions, resolves #59

### LINKED ISSUE #59: Add support for variadic functions and parameters
New version of PHP (5.6) extends `ReflectionFunction` and `ReflectionParameter` with new method: `isVariadic()`. 

PHP-Token-Reflection missed this functionality.

### PR DESCRIPTION
**Pull request by lisachenko**
This PR adds a support for variadics parsing in PHP>=5.6.0

### CODE REVIEW

**Comment by lisachenko** [comment]
@Andrewsville do you keep working on this project? or it's abandoned and I can create a fork and maintain it?

Your library is really good and I used it to build an aspect-oriented framework. However, to support new versions of PHP, some of Reflection classes should be updated.

**Comment by lisachenko** [comment]
@TomasVotruba thanks, switching to your fork.

**Comment by TomasVotruba** [comment]
@lisachenko It's still WIP and that fork is going to be standalone lib just for ApiGen purposes. I'm not planning to maintain 1:1 compatibility with this original package.

I'd recommend you to wait for new stable I shall release and see, if is suits your needs.

**Comment by lisachenko** [comment]
@TomasVotruba it's better to use a maintained soft, so I'd better to help you or adopt my framework for your fork )

**Comment by TomasVotruba** [comment]
@lisachenko I definitely agree - better working than perfect - and I'm glad to hear that. Any help much appreciated.

**Pull request closed without merging**
